### ISSUE TITLE
ios模拟器运行报错

### ISSUE THREAD

**Issue by hrxiang** [OpenIMSDK/Open-IM-SDK-Flutter#55]
模拟器/真机：
```
flutter_openim_sdk:
       git:
          url: https://github.com/OpenIMSDK/Open-IM-SDK-Flutter.git
          ref: fix-ios-simulator

```

仅真机：
```
dependencies:
  flutter_openim_sdk: ^1.0.6
```
